AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  selfless-service-updates

  Automatically apply ElastiCache self-service updates.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: selfless-service-updates
    Description: Automatically apply ElastiCache self-service updates.
    Author: Theron Luhn
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - elasticache
      - redis
      - memcache
      - maintenance
      - update
    HomePageUrl: https://github.com/luhn/selfless-service-updates
    SemanticVersion: 0.1.1
    SourceCodeUrl: https://github.com/luhn/selfless-service-updates

Parameters:
  CronExpression:
    Type: String
    Default: "0 10 ? * MON *"
    Description: >
      Enter a cron expression for when the run the function.  Default is
      "0 10 ? * MON *", meaning Monday at 10:00 UTC.

Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.handler
      MemorySize: 128
      Timeout: 120
      Runtime: python3.8
      Role: !GetAtt ExecutionRole.Arn

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: elasticache
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - elasticache:DescribeServiceUpdates
            - elasticache:DescribeUpdateActions
            - elasticache:BatchApplyUpdateAction
            Resource: "*"

  Cron:
    Type: AWS::Events::Rule
    Properties:
      Description: "Trigger self-service updates."
      ScheduleExpression: !Sub "cron(${CronExpression})"
      State: ENABLED
      Targets:
        - Arn: !GetAtt MainFunction.Arn
          Id: Function

  CronPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: MainFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt Cron.Arn
