AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  selfless-service-updates

  Sample SAM Template for selfless-service-updates

Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.lambda_handler
      Timeout: 120
      Runtime: python3.8
